### ISSUE TITLE
https://github.com/SinaXhpm/SinChi

### ISSUE THREAD

**Issue by rezablack07** [SinaXhpm/SinChi#1]
chera install nemishe dige , error mideh baed az nasb , lotfan dorostesh konid

**Comment by SinaXhpm** [comment]
ارورتون رو توی گروه بگید تا راه حلش رو بگن

**Comment by javad11sa** [comment]
سیناوجان سلام ااومدم پیویت تلگرام جواب ندادی اسمم جواد هستش میخوام هیلپو شخصی سازی کنی واسم هزینشم میدم
